//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddInManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddInManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppFolder {
            get {
                return ResourceManager.GetString("AppFolder", resourceCulture);
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Develop_16 {
            get {
                object obj = ResourceManager.GetObject("Develop_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Develop_32 {
            get {
                object obj = ResourceManager.GetObject("Develop_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static string LoadCancelled {
            get {
                return ResourceManager.GetString("LoadCancelled", resourceCulture);
            }
        }
        
        public static string LoadFailed {
            get {
                return ResourceManager.GetString("LoadFailed", resourceCulture);
            }
        }
        
        public static string LoadFileFilter {
            get {
                return ResourceManager.GetString("LoadFileFilter", resourceCulture);
            }
        }
        
        public static string LoadSucceed {
            get {
                return ResourceManager.GetString("LoadSucceed", resourceCulture);
            }
        }
        
        public static string NoItemsSelected {
            get {
                return ResourceManager.GetString("NoItemsSelected", resourceCulture);
            }
        }
        
        // --- MainWindow strings ---
        
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        public static string TabCommands {
            get {
                return ResourceManager.GetString("TabCommands", resourceCulture);
            }
        }
        
        public static string TabApplications {
            get {
                return ResourceManager.GetString("TabApplications", resourceCulture);
            }
        }
        
        public static string SearchWatermark {
            get {
                return ResourceManager.GetString("SearchWatermark", resourceCulture);
            }
        }
        
        public static string TooltipSelectAllCommands {
            get {
                return ResourceManager.GetString("TooltipSelectAllCommands", resourceCulture);
            }
        }
        
        public static string TooltipDeselectCommands {
            get {
                return ResourceManager.GetString("TooltipDeselectCommands", resourceCulture);
            }
        }
        
        public static string TooltipExpandAll {
            get {
                return ResourceManager.GetString("TooltipExpandAll", resourceCulture);
            }
        }
        
        public static string TooltipCollapseAll {
            get {
                return ResourceManager.GetString("TooltipCollapseAll", resourceCulture);
            }
        }
        
        public static string TooltipSelectAllApps {
            get {
                return ResourceManager.GetString("TooltipSelectAllApps", resourceCulture);
            }
        }
        
        public static string TooltipDeselectApps {
            get {
                return ResourceManager.GetString("TooltipDeselectApps", resourceCulture);
            }
        }
        
        public static string TooltipExpandAllApps {
            get {
                return ResourceManager.GetString("TooltipExpandAllApps", resourceCulture);
            }
        }
        
        public static string TooltipCollapseAllApps {
            get {
                return ResourceManager.GetString("TooltipCollapseAllApps", resourceCulture);
            }
        }
        
        public static string ContextMenuRun {
            get {
                return ResourceManager.GetString("ContextMenuRun", resourceCulture);
            }
        }
        
        public static string ContextMenuLoad {
            get {
                return ResourceManager.GetString("ContextMenuLoad", resourceCulture);
            }
        }
        
        public static string ContextMenuRemove {
            get {
                return ResourceManager.GetString("ContextMenuRemove", resourceCulture);
            }
        }
        
        public static string ContextMenuReload {
            get {
                return ResourceManager.GetString("ContextMenuReload", resourceCulture);
            }
        }
        
        public static string ContextMenuOpenInExplorer {
            get {
                return ResourceManager.GetString("ContextMenuOpenInExplorer", resourceCulture);
            }
        }
        
        public static string ContextMenuAssemblyInfo {
            get {
                return ResourceManager.GetString("ContextMenuAssemblyInfo", resourceCulture);
            }
        }
        
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        public static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        public static string LabelNotes {
            get {
                return ResourceManager.GetString("LabelNotes", resourceCulture);
            }
        }
        
        public static string BtnRun {
            get {
                return ResourceManager.GetString("BtnRun", resourceCulture);
            }
        }
        
        public static string BtnLoad {
            get {
                return ResourceManager.GetString("BtnLoad", resourceCulture);
            }
        }
        
        public static string BtnRemove {
            get {
                return ResourceManager.GetString("BtnRemove", resourceCulture);
            }
        }
        
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        public static string MenuSaveToAddins {
            get {
                return ResourceManager.GetString("MenuSaveToAddins", resourceCulture);
            }
        }
        
        public static string MenuSaveToLocal {
            get {
                return ResourceManager.GetString("MenuSaveToLocal", resourceCulture);
            }
        }
        
        // --- Status messages ---
        
        public static string StatusSelectedAll {
            get {
                return ResourceManager.GetString("StatusSelectedAll", resourceCulture);
            }
        }
        
        public static string StatusDeselectedAll {
            get {
                return ResourceManager.GetString("StatusDeselectedAll", resourceCulture);
            }
        }
        
        public static string StatusInvertedSelection {
            get {
                return ResourceManager.GetString("StatusInvertedSelection", resourceCulture);
            }
        }
        
        public static string StatusLoading {
            get {
                return ResourceManager.GetString("StatusLoading", resourceCulture);
            }
        }
        
        public static string StatusLoadError {
            get {
                return ResourceManager.GetString("StatusLoadError", resourceCulture);
            }
        }
        
        public static string StatusNoCommandSelected {
            get {
                return ResourceManager.GetString("StatusNoCommandSelected", resourceCulture);
            }
        }
        
        public static string StatusRunError {
            get {
                return ResourceManager.GetString("StatusRunError", resourceCulture);
            }
        }
        
        public static string StatusNotExecutableCommand {
            get {
                return ResourceManager.GetString("StatusNotExecutableCommand", resourceCulture);
            }
        }
        
        public static string StatusSaveSuccessReload {
            get {
                return ResourceManager.GetString("StatusSaveSuccessReload", resourceCulture);
            }
        }
        
        public static string StatusSaveSuccess {
            get {
                return ResourceManager.GetString("StatusSaveSuccess", resourceCulture);
            }
        }
        
        public static string StatusReloadNotFound {
            get {
                return ResourceManager.GetString("StatusReloadNotFound", resourceCulture);
            }
        }
        
        public static string StatusReloadFileNotFound {
            get {
                return ResourceManager.GetString("StatusReloadFileNotFound", resourceCulture);
            }
        }
        
        public static string StatusReloading {
            get {
                return ResourceManager.GetString("StatusReloading", resourceCulture);
            }
        }
        
        public static string StatusReloadError {
            get {
                return ResourceManager.GetString("StatusReloadError", resourceCulture);
            }
        }
        
        public static string StatusReloadFailed {
            get {
                return ResourceManager.GetString("StatusReloadFailed", resourceCulture);
            }
        }
        
        public static string StatusReloadSuccess {
            get {
                return ResourceManager.GetString("StatusReloadSuccess", resourceCulture);
            }
        }
        
        public static string StatusOpenLocationError {
            get {
                return ResourceManager.GetString("StatusOpenLocationError", resourceCulture);
            }
        }
        
        public static string StatusInvalidPath {
            get {
                return ResourceManager.GetString("StatusInvalidPath", resourceCulture);
            }
        }
        
        public static string StatusAssemblyNotFound {
            get {
                return ResourceManager.GetString("StatusAssemblyNotFound", resourceCulture);
            }
        }
        
        public static string StatusAssemblyLoadError {
            get {
                return ResourceManager.GetString("StatusAssemblyLoadError", resourceCulture);
            }
        }
        
        // --- Assembly info dialog ---
        
        public static string AssemblyInfoTitle {
            get {
                return ResourceManager.GetString("AssemblyInfoTitle", resourceCulture);
            }
        }
        
        public static string AssemblyInfoAssembly {
            get {
                return ResourceManager.GetString("AssemblyInfoAssembly", resourceCulture);
            }
        }
        
        public static string AssemblyInfoVersion {
            get {
                return ResourceManager.GetString("AssemblyInfoVersion", resourceCulture);
            }
        }
        
        public static string AssemblyInfoFullName {
            get {
                return ResourceManager.GetString("AssemblyInfoFullName", resourceCulture);
            }
        }
        
        public static string AssemblyInfoDependencies {
            get {
                return ResourceManager.GetString("AssemblyInfoDependencies", resourceCulture);
            }
        }
        
        // --- AssemblySelectorWindow strings ---
        
        public static string AssemblySelectorTitle {
            get {
                return ResourceManager.GetString("AssemblySelectorTitle", resourceCulture);
            }
        }
        
        public static string AssemblySelectorPrompt1 {
            get {
                return ResourceManager.GetString("AssemblySelectorPrompt1", resourceCulture);
            }
        }
        
        public static string AssemblySelectorPrompt2 {
            get {
                return ResourceManager.GetString("AssemblySelectorPrompt2", resourceCulture);
            }
        }
        
        public static string BtnBrowse {
            get {
                return ResourceManager.GetString("BtnBrowse", resourceCulture);
            }
        }
        
        public static string BtnOk {
            get {
                return ResourceManager.GetString("BtnOk", resourceCulture);
            }
        }
        
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        // --- DependencyGraphWindow strings ---
        
        public static string DependencyTitle {
            get {
                return ResourceManager.GetString("DependencyTitle", resourceCulture);
            }
        }
        
        public static string BtnRefreshAnalysis {
            get {
                return ResourceManager.GetString("BtnRefreshAnalysis", resourceCulture);
            }
        }
        
        public static string DependencyHelpText {
            get {
                return ResourceManager.GetString("DependencyHelpText", resourceCulture);
            }
        }
        
        public static string DependencyLoadedPlugins {
            get {
                return ResourceManager.GetString("DependencyLoadedPlugins", resourceCulture);
            }
        }
        
        public static string DependencyReferencedAssemblies {
            get {
                return ResourceManager.GetString("DependencyReferencedAssemblies", resourceCulture);
            }
        }
        
        public static string DependencyReady {
            get {
                return ResourceManager.GetString("DependencyReady", resourceCulture);
            }
        }
        
        public static string DependencyAnalyzed {
            get {
                return ResourceManager.GetString("DependencyAnalyzed", resourceCulture);
            }
        }
        
        public static string DependencyDetailHeader {
            get {
                return ResourceManager.GetString("DependencyDetailHeader", resourceCulture);
            }
        }
        
        // --- UnhandledExceptionDialog strings ---
        
        public static string ExceptionTitle {
            get {
                return ResourceManager.GetString("ExceptionTitle", resourceCulture);
            }
        }
        
        public static string ExceptionHeader {
            get {
                return ResourceManager.GetString("ExceptionHeader", resourceCulture);
            }
        }
        
        public static string ExceptionStackTrace {
            get {
                return ResourceManager.GetString("ExceptionStackTrace", resourceCulture);
            }
        }
        
        public static string BtnCopyDetails {
            get {
                return ResourceManager.GetString("BtnCopyDetails", resourceCulture);
            }
        }
        
        public static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        public static string CopiedTitle {
            get {
                return ResourceManager.GetString("CopiedTitle", resourceCulture);
            }
        }
        
        public static string CopiedMessage {
            get {
                return ResourceManager.GetString("CopiedMessage", resourceCulture);
            }
        }
        
        // --- LogViewerWindow strings ---
        
        public static string LogViewerTitle {
            get {
                return ResourceManager.GetString("LogViewerTitle", resourceCulture);
            }
        }
        
        public static string BtnClearLog {
            get {
                return ResourceManager.GetString("BtnClearLog", resourceCulture);
            }
        }
        
        public static string BtnExport {
            get {
                return ResourceManager.GetString("BtnExport", resourceCulture);
            }
        }
        
        public static string ChkAutoScroll {
            get {
                return ResourceManager.GetString("ChkAutoScroll", resourceCulture);
            }
        }
        
        public static string ColTime {
            get {
                return ResourceManager.GetString("ColTime", resourceCulture);
            }
        }
        
        public static string ColLevel {
            get {
                return ResourceManager.GetString("ColLevel", resourceCulture);
            }
        }
        
        public static string ColMessage {
            get {
                return ResourceManager.GetString("ColMessage", resourceCulture);
            }
        }
        
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        public static string LogStatusFormat {
            get {
                return ResourceManager.GetString("LogStatusFormat", resourceCulture);
            }
        }
        
        public static string LogExportTitle {
            get {
                return ResourceManager.GetString("LogExportTitle", resourceCulture);
            }
        }
        
        public static string LogExportFilter {
            get {
                return ResourceManager.GetString("LogExportFilter", resourceCulture);
            }
        }
        
        public static string LogExportedTo {
            get {
                return ResourceManager.GetString("LogExportedTo", resourceCulture);
            }
        }
        
        public static string LogExportSuccess {
            get {
                return ResourceManager.GetString("LogExportSuccess", resourceCulture);
            }
        }
        
        public static string LogExportFailed {
            get {
                return ResourceManager.GetString("LogExportFailed", resourceCulture);
            }
        }
        
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        // --- FolderTooBigDialog strings ---
        
        public static string FolderTooBigLine1 {
            get {
                return ResourceManager.GetString("FolderTooBigLine1", resourceCulture);
            }
        }
        
        public static string FolderTooBigLine2 {
            get {
                return ResourceManager.GetString("FolderTooBigLine2", resourceCulture);
            }
        }
        
        public static string FolderTooBigLine3 {
            get {
                return ResourceManager.GetString("FolderTooBigLine3", resourceCulture);
            }
        }
        
        public static string FolderTooBigLine4 {
            get {
                return ResourceManager.GetString("FolderTooBigLine4", resourceCulture);
            }
        }
        
        public static string FolderTooBigLine5 {
            get {
                return ResourceManager.GetString("FolderTooBigLine5", resourceCulture);
            }
        }
        
        public static string FolderTooBigLine6 {
            get {
                return ResourceManager.GetString("FolderTooBigLine6", resourceCulture);
            }
        }
        
        // --- FailedToRunECDialog strings ---
        
        public static string FailedToRunEC {
            get {
                return ResourceManager.GetString("FailedToRunEC", resourceCulture);
            }
        }
        
        // --- Language switcher strings ---
        
        public static string LangMenu {
            get {
                return ResourceManager.GetString("LangMenu", resourceCulture);
            }
        }
        
        public static string LangChinese {
            get {
                return ResourceManager.GetString("LangChinese", resourceCulture);
            }
        }
        
        public static string LangEnglish {
            get {
                return ResourceManager.GetString("LangEnglish", resourceCulture);
            }
        }
        
        public static string LangJapanese {
            get {
                return ResourceManager.GetString("LangJapanese", resourceCulture);
            }
        }
        
        public static string LangChangeTitle {
            get {
                return ResourceManager.GetString("LangChangeTitle", resourceCulture);
            }
        }
        
        public static string LangChangeMessage {
            get {
                return ResourceManager.GetString("LangChangeMessage", resourceCulture);
            }
        }
    }
}
